### ISSUE TITLE
automatic client login seems doesnt work

### ISSUE THREAD

**Issue by adamramadhan** [JosephChuks/HestiaCP-WHMCS-Module#2]
1. CSRF needs to be turned off somehow
2. after click stuck at the login page

**Comment by JosephChuks** [comment]
HestiaCP doesn't have automatic client Login like cPanel, But you can implement a workaround by modifying hestiacp core files (web template)

`usr/local/hestia/web/`

Note that changes will be overwritten if you update hestiacp
