### ISSUE TITLE
Module Command Error 9

### ISSUE THREAD

**Issue by ereddadigitals** [JosephChuks/HestiaCP-WHMCS-Module#3]
I received this error "Module Command Error 9" to click create at WHMCS command. Any help

**Comment by JosephChuks** [comment]
Can you be specific of the command you are trying to run?

**Comment by JosephChuks** [comment]
See HestiaCP Error codes: https://hestiacp.com/docs/server-administration/rest-api.html

**Comment by ereddadigitals** [comment]
Create account

**Comment by ereddadigitals** [comment]
> Can you be specific of the command you are tryif know how use module 

> Can you be specific of the command you are trying to run?

Please help solve this issues, contact me on WhatsApp at +233245152060
Thank you
